version: 2016.2.{build}
shallow_clone: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:
    secure: XBCyPFZbO55cEI6tMsd1Ts3O7sXF3IFCxGPYQGJbVae48G9j9miONIHmDwzG4iLG
  SONARQUBE_USER:
    secure: xQ0uPUuuXgtVDqMsTjpfaQ==
  SONARQUBE_PASSWORD:
    secure: feupc6DdN7VnWMEziKIEZQ==
cache: .\MYOB.API.SDK\SDK\MYOB.API.SDK.snk
build_script:
- build.bat
artifacts:
- path: .\Artefacts\Nuget\Release\*.nupkg
  name: Release
- path: .\Artefacts\Nuget\Candidate\*.nupkg
  name: Candidate
- path: .\Artefacts\Coverage\output.xml
  name: Coverage
deploy:
- provider: NuGet
  api_key:
    secure: LlFtlduQCvv8/wLHFr7i9bLjEdmXklNHtl4X0dbU3qe6b2fduuSGzLlytZGuFr2a
  skip_symbols: true
  artifact: Release
  on:
    branch: release
- provider: NuGet
  api_key:
    secure: LlFtlduQCvv8/wLHFr7i9bLjEdmXklNHtl4X0dbU3qe6b2fduuSGzLlytZGuFr2a
  skip_symbols: true
  artifact: Candidate
  on:
    branch: candidate
- provider: NuGet
  server: https://www.myget.org/F/myob-developers/api/v2
  api_key:
    secure: OGw616WsfGBUWoVi1NZFVekoCyXoqi1f93v8GJJ8Y1DgcH5utdKg0yX2FGkFkXfj
  artifact: Release
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/a5f4ffd724543d128fff
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
on_success:
- cmd: >-
    sonar.bat